version: '3.8'

services:
  redis-db:
    extends:
      file: ./services/docker-compose-redis.yml
      service: redis_db
    ports:
      - 7379:6379

  db:
    extends:
      file: ./services/docker-compose-db.yml
      service: db

  smart-contract-verifier:
    extends:
      file: ./services/docker-compose-smart-contract-verifier.yml
      service: smart-contract-verifier

  visualizer:
    extends:
      file: ./services/docker-compose-visualizer.yml
      service: visualizer

  sig-provider:
    extends:
      file: ./services/docker-compose-sig-provider.yml
      service: sig-provider

  stats-db:
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats-db

  stats:
    depends_on:
      - stats-db
      - db
    extends:
      file: ./services/docker-compose-stats.yml
      service: stats

  proxy:
    depends_on:
      - stats
      - visualizer
    extends:
      file: ./services/docker-compose-nginx.yml
      service: proxy
    environment:
      BACK_PROXY_PASS: http://host.docker.internal:4000
      FRONT_PROXY_PASS: http://host.docker.internal:3000
